### ISSUE TITLE
How to solve: Protoc failed when building kuksa-databroker via cargo (Win10)

### ISSUE THREAD

**Issue by XavierDai** [eclipse/kuksa.val#562] opened 2023-05-17 05:53 UTC
command: cargo build --examples --bins

Error: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: proto/sdv/databroker/v1/broker.proto: No such file or directory\r\n" }

**Comment by argerus** [comment] 2023-05-17 05:57
This is caused by Windows lack of support for symbolic links (at least I'm pretty sure of this).

I don't use windows, but I have a vague memory of there being some type of configuration for git on windows, where you can "enable" support for symbolic links. Not sure this is true (or why it wouldn't be enabled by default if so).

**Comment by lukasmittag** [comment] 2024-02-09 08:34
No further action here. Closing

**Closed by lukasmittag** 2024-02-09 08:34 UTC
Labels: question
