### ISSUE TITLE
Facing kuala-grpc error with statusCode: UNIMPLEMENTED

### ISSUE THREAD

**Issue by mhatrepratik11** [eclipse/kuksa.val#489] opened 2023-02-24 22:22 UTC
**Hi Team,**
**I am facing a issue while connecting to kuksa-val-server using kuksa-client with grpc protocol.**

I have kuksa-val-server up and running and exposed ports please see in the below screenshots:

<img width="570" alt="Kuksa-Val-Server is running" src="https://user-images.githubusercontent.com/10961872/221299894-67f214b8-f85d-41d5-ae8b-0d44dab83a84.png">

See the exposed ports in the below screenshot:
<img width="1392" alt="Port exposed and forwarded" src="https://user-images.githubusercontent.com/10961872/221304371-2af17a1b-8945-45ef-a891-03506a1e8f2a.png">

I am trying to connect to kuala-val-server using kuala-client using VSSClient as you can see in the below screenshot.

**While trying to connect with python code:** 

```
from kuksa_client.grpc import VSSClient

with VSSClient('localhost', 50051) as client:
    current_values = client.get_current_values([
        'Vehicle.Speed',
    ])
    print(current_values['Vehicle.Speed'].value)
```

**_I am getting error with grpc statusCode: 12 (UNIMPLEMENTED) as shown below in the screenshot:
kuksa_client.grpc.VSSClientError: ({'code': 12, 'reason': 'unimplemented', 'message': ''}, [])_**

<img width="570" alt="Kuksa-grpc-unimpleted-error" src="https://user-images.githubusercontent.com/10961872/221301241-db85050a-52bc-4220-bfae-001da145e749.png">

**_NOTE: I am able to connect to kuksa-val-server through “ws” protocol by using code shown in the screenshot below:_**

<img width="570" alt="Kuksa-Client-WS-Connected" src="https://user-images.githubusercontent.com/10961872/221301868-d29f5563-fbbd-4e77-af13-c2fcc6855dad.png">

**Thanks in Advance !**

**Comment by SebastianSchildt** [comment] 2023-02-25 11:25
Hi, 

i understand this is a bit confusing currently. Basically  there are not all combinations between client and server that work.  Maybe this helps


| Server  | Client  |  Py API  | Comment
|--------|---|---|---|
|kuksa-databroker  (Rust)  | databroker-cli or [kuksa-client](https://pypi.org/project/kuksa-client/)  |  [kuksa-client](https://pypi.org/project/kuksa-client/), [all variants](https://github.com/eclipse/kuksa.val/tree/master/kuksa-client/docs/examples) , sync or async recommended   | Recommended for new designs
| KUKSA val-server (C++)   | [kuksa-client](https://pypi.org/project/kuksa-client/) or [kuksa-viss-client][(https://pypi.org/project/kuksa-client/](https://pypi.org/project/kuksa-viss-client/) (deprecated)  | Websocket: [kuksa-client](https://pypi.org/project/kuksa-client/) only [threaded API](https://github.com/eclipse/kuksa.val/blob/master/kuksa-client/docs/examples/threaded.md)  , Websocket and GRPC:  [kuksa-viss-client](https://pypi.org/project/kuksa-viss-client/)  (deprecated)  |


An important thing is that val-server GRPC != databroker GRPC currently. In a nuthshell, it depends where you are coming from:

If you start fresh, use databroker + kuksa-client. Don't use the kuksa-val compatible threaded API, as that is the slowest. The [quickstart](https://github.com/eclipse/kuksa.val/blob/master/doc/quickstart.md) will get you, well, started

If you have a dependency on val-server, use Websocket with kuksa-client. That is better tested than the GRPC version of val-server. By using the threaded API, it will be easy to later switch to databroker, if it fulfils your need

Maybe interesting:: If the reason for val-server is authorisation: We are working on bringing this feature - in an improved way -  to databroker currently.

If none of the solutions quite fit, what you are trying to do, please let us now, what your requirements are. Especially if you have something currently only fulfilled by val-server. 

@lukasmittag : Maybe we should put something like this in the differences documentation

**Comment by mhatrepratik11** [comment] 2023-02-25 22:15
**Thank you so much for your help @SebastianSchildt** 

**That was crystal clear explanation and very helpful. Now its very clear to decide what to use.**

I have started kuksa fresh and currently exploring. I am flexible to use whatever is recommended. I tried using kuksa-databroker with kuala-client python API but facing a issue.

**I need 1 more help regarding the same.**

I have tried the things listed on kuksa quickstart page. Below are the some use cases that I have tried from the [kuksa quickstart](https://github.com/eclipse/kuksa.val/blob/master/doc/quickstart.md) page:


_**1. Used docker to run kuksa-databroker and kuksa-client**_

Ran kuksa-databroker with docker using below command
`docker run -it --rm --net=host ghcr.io/eclipse/kuksa.val/databroker:master`

Ran kuksa-client with docker using below command
`docker run -it --rm --net=host ghcr.io/eclipse/kuksa.val/kuksa-client:master --port 55555 --protocol grpc --insecure`

**RESULT:  SUCCESS - Working fine and able to fire commands through kuksa-client on kuksa-databroker**

_**2. Used docker to run kuksa-databroker and tried connecting with kuksa-client with python API**_

Tried running kuksa-databroker with docker using below 2 commands - 

i) First tried with the simple docker command which is given on kuksa quickstart then tried kuksa-client with the python code given below.
`docker run -it --rm --net=host ghcr.io/eclipse/kuksa.val/databroker:master`

Used below kuksa-client python code to connect with kuksa-databroker

```
from kuksa_client.grpc import VSSClient
from kuksa_client.grpc import Datapoint

import time

with VSSClient('127.0.0.1', 55555) as client:
    for speed in range(0, 100):
        client.set_current_values({
            'Vehicle.Speed': Datapoint(speed),
        })
        print(f"Feeding Vehicle.Speed to {speed}")
        time.sleep(1)
print("Finished.")
```

**NOTE: Tried with changing IP address in VSSClient as well. i.e. Used "0.0.0.0:55555" instead "127.0.0.1:55555".
with VSSClient('0.0.0.0', 55555) as client:**

**RESULT:   ERROR - Getting below error as** 
**kuksa_client.grpc.VSSClientError: ({'code': 14, 'reason': 'unavailable', 'message': 'failed to connect to all addresses'}, [])**

**Please see screenshot below**
<img width="500" alt="grpc-error-databroker - 55556" src="https://user-images.githubusercontent.com/10961872/221381424-d21ddafa-a4c0-4f1f-a67a-4e460659db24.png">


ii) After that tried docker command which will publish port 55556 and tried setting up the environment variables to change the ip address and port of the container then tried kuksa-client with the python code given below.
`docker run -it --rm --env KUKSA_DATA_BROKER_ADDR=127.0.0.1 --env KUKSA_DATA_BROKER_PORT=55556 --net=host ghcr.io/eclipse/kuksa.val/databroker:master --publish 55556:55556`

Used below kuksa-client python code to connect with kuksa-databroker

```
from kuksa_client.grpc import VSSClient
from kuksa_client.grpc import Datapoint

import time

with VSSClient('127.0.0.1', 55556) as client:
    for speed in range(0, 100):
        client.set_current_values({
            'Vehicle.Speed': Datapoint(speed),
        })
        print(f"Feeding Vehicle.Speed to {speed}")
        time.sleep(1)
print("Finished.")
```

**RESULT:   ERROR - Getting below error as** 
**kuksa_client.grpc.VSSClientError: ({'code': 14, 'reason': 'unavailable', 'message': 'failed to connect to all addresses'}, [])**

**Please see screenshot below**
<img width="500" alt="grpc-error-databroker - 55555" src="https://user-images.githubusercontent.com/10961872/221381518-c935037d-f0a4-4d8b-9969-4c300f51f17e.png">


**_Is there anyway to connect from python API to the kuksa-databroker which is running in the docker container ?_**

**_Or I will have to run kuksa-databroker locally and then try to connect via kuksa-client python API ?_**

**_Please Suggest._**

**Comment by lukasmittag** [comment] 2023-02-27 07:23
Hey,

I don't know if your screenshots are correct, but they seem to both use 55556 as port. Else it looks good and should work I think.

**Comment by SebastianSchildt** [comment] 2023-02-27 08:12
Maybe some issue with your network setup. I do see you are using 

```
docker run -it --rm --env KUKSA_DATA_BROKER_ADDR=127.0.0.1 --env KUKSA_DATA_BROKER_PORT=55556 --net=host ghcr.io/eclipse/kuksa.val/databroker:master --publish 55556:55556
```

You should not combine `--publish`with `--net==host` ( I think it will ignore --publish , put also not even sure it is in the correct place. Also do nit use this `--env KUKSA_DATA_BROKER_ADDR=127.0.0.1 `, because default is 0.0.0.0 (and when connecting from outisde container depending on the docker network setup it is not necessarily the case that the origin ist 127.0.0.1 from the perspective of the container.

I think the root cause is, you are using "Docker Desktop" (at least judging from the icon in the menu bar). I have no experience with it, but the documentation https://docs.docker.com/network/host/ says 

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

I can say docker --net=host works for Mac OS on  https://rancherdesktop.io

With docker desktop, try starting the databroker like this

```
 docker run -it --rm  --publish 55556:55556 ghcr.io/eclipse/kuksa.val/databroker:master  --port 55556
```


I think you should be able to connect from host using 127.0.0.1:55556

**Comment by mhatrepratik11** [comment] 2023-02-27 18:35
**Thank you so much @SebastianSchildt**

It’s working for me with the docker command provided above. Also thanks for quick replies and other shared knowledge. 

I think we can close this issue now as I am good to move forward. Please give me go ahead to close this issue or you can close it.

**Thanks again !**

**Comment by SebastianSchildt** [comment] 2023-02-27 18:44
Good, that it works for you now. I will close this, feel free to open a new issue in case of problems

**Closed by SebastianSchildt** 2023-02-27 18:44 UTC
