### ISSUE TITLE
Interface function should always use 'VSSPath' instead of string for `IVssDatabase`

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#179] opened 2021-04-22 15:18 UTC
getMetaData should also use `VSSPath` as parameter

https://github.com/eclipse/kuksa.val/blob/761420934fd7cf3497032565a21c937f35c7c0d3/include/interface/IVssDatabase.hpp#L33

**Comment by SebastianSchildt** [comment] 2021-04-22 19:08
Duplicate of #157

**Closed by SebastianSchildt** 2021-04-22 19:08 UTC
Labels: duplicate
