### ISSUE TITLE
kuksa_viss_client does not show the correct version

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#254] opened 2022-03-24 17:25 UTC
If I start local modified `kuksa_viss_client`, it showed me a version number, which is not compatible:

 ```
(.venv) ~/c/k/kuksa_viss_client> python __main__.py
Welcome to kuksa viss client version 0.2.0
...
```

Additionally, [__main__.py](https://github.com/eclipse/kuksa.val/blob/master/kuksa_viss_client/__main__.py) seems not use the [__init__.py](https://github.com/eclipse/kuksa.val/blob/master/kuksa_viss_client/__init__.py) in the same folder, which could be confused.

**Comment by SebastianSchildt** [comment] 2022-11-23 12:53
Probably outdated, as the client is largely rewritten now, but might want to check behavior on current client, I do notice installed locally ,it refers to itself as
`Welcome to Kuksa Client version 0.0.2.50`

That "feels" at least too long for a version number.

What is expected behavior @romainletendart ?

**Comment by romainletendart** [comment] 2022-11-23 13:57
As we [configured it](https://github.com/eclipse/kuksa.val/blob/f1e1ce9f5f219a19048d150246bb6562cd969820/kuksa-client/pyproject.toml#L13-L14), it should be `0.0.2-50`. I don't know why the dash gets translated into a dot.

In any case, `0.0.2.5` seems to be a valid python package version according to [PEP 440](https://peps.python.org/pep-0440/#public-version-identifiers). It seems however `0.0.2.post5` would be more appropriate here.

I don't have the rationale behind our custom format. It seems to me the [default format](https://setuptools-git-versioning.readthedocs.io/en/stable/options/dirty_template.html#default-value) is a more sensible choice as it includes the commit hash which is handier to find out which commit was used to generate the package.

Anyway everything I said above only applies to dev or dirty packages.
For release packages, the git tag will be used as is e.g. `0.0.2` so no issues for that one.

We just have to decide if dev and/or dirty package version formats are still OK as they are.
Regarding the original issue, I think the version is "correct" according to what has been configured so the issue isn't there anymore.

**Comment by SebastianSchildt** [comment] 2022-11-29 18:23
Works (better) with new kuksa_client.

Closing this, until new specific issues pop up

**Closed by SebastianSchildt** 2022-11-29 18:23 UTC
Labels: Client
